### ISSUE TITLE
Assertion Error happen when enter 作業區

### ISSUE THREAD

**Issue by Wilson1211** [lantw44/ceiba-dl#14]
Traceback (most recent call last):
  File "/usr/local/bin/ceiba-dl", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "/usr/local/bin/ceiba-dl", line 141, in run_get
    end_download_callback=end_callback)
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/__init__.py", line 388, in run
    download_progress_callback, end_download_callback)
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/__init__.py", line 214, in download_file
    node = self.vfs.open(path)
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/usr/local/lib/python3.5/site-packages/ceiba_dl/vfs.py", line 1493, in fetch
    ['br'] * len(hw_show_description_element)
AssertionError

**Comment by lantw44** [comment]
Since you hit an assertion error, it will be nice to know values of variables used inside the line of assert.
