### ISSUE TITLE
Assertion Error when there are multiple courses with the same Chinese name

### ISSUE THREAD

**Issue by domen111** [lantw44/ceiba-dl#17]
It is possible to take multiple courses with the same name, such as "專題研究", in one semester at NTU. However, this situation causes the following AsssertionError:

```
Traceback (most recent call last):
  File "/tmp2/b05902094/ceiba-dl/ceiba-dl.py", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "/tmp2/b05902094/ceiba-dl/ceiba-dl.py", line 139, in run_get
    succeeded = succeeded and get.run(path, retry=args.retry,
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 387, in run
    return self.download_file(path, retry + 1,
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 214, in download_file
    node = self.vfs.open(path)
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/vfs.py", line 837, in fetch
    assert sn == courses[name]['sn']
AssertionError
```

**Comment by lantw44** [comment]
這個感覺有點麻煩，因為目前是用課程名稱當資料夾名稱，所以課程名稱不能重複。如果要解決問題，可能只能按照課程出現順序在課程名稱後面加 1、2、3 之類的編號，因為這些課程不一定有 CEIBA 課程代號。你有打算提供 patch 修正這個問題嗎？
