### ISSUE TITLE
Assertion Error when a grade is not announced

### ISSUE THREAD

**Issue by domen111** [lantw44/ceiba-dl#18]
One of the courses I took still shows a grade as "未公佈". This causes the following AssertionError:

```
Traceback (most recent call last):
  File "/tmp2/b05902094/ceiba-dl/ceiba-dl.py", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "/tmp2/b05902094/ceiba-dl/ceiba-dl.py", line 139, in run_get
    succeeded = succeeded and get.run(path, retry=args.retry,
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 387, in run
    return self.download_file(path, retry + 1,
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  [Previous line repeated 1 more time]
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/__init__.py", line 214, in download_file
    node = self.vfs.open(path)
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/tmp2/b05902094/ceiba-dl/ceiba_dl/vfs.py", line 2118, in fetch
    assert grade['grade'] == grade_row_grade
AssertionError
```

**Comment by lantw44** [comment]
等號兩邊的值分別是？看起來是網頁顯示「未公佈」但 CEIBA API 給的字串不一樣？
