### ISSUE TITLE
Class may not have contents

### ISSUE THREAD

**Issue by wheatdog** [lantw44/ceiba-dl#7]
I got this assertion while running `ceiba-dl get`.
```                                                                            
Traceback (most recent call last):
  File "/usr/bin/ceiba-dl", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "/usr/bin/ceiba-dl", line 141, in run_get
    end_download_callback=end_callback)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 388, in run                                                                              
    download_progress_callback, end_download_callback)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file                                                                    
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file                                                                    
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file                                                                    
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 214, in download_file                                                                    
    node = self.vfs.open(path)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 902, in fetch
    assert set(result.keys()) - set(optional_keys) == set(result_keys)
AssertionError
```
Some investigate,
```
================================================================================                                                                               
機器學習技法                                                                                                                                                   
result.keys()                                                                                                                                                  
dict_keys(['lang', 'course_info', 'teacher_info', 'homeworks'])                                                                                                
optional_keys
['bulletin', 'board', 'course_grade', 'homeworks']
result_keys
['lang', 'course_info', 'teacher_info', 'contents', 'content_files']
================================================================================  
```
Ceiba Page for the class, maybe it is using iframe.
![image](https://user-images.githubusercontent.com/7741908/50198162-57cb8480-0385-11e9-8ca2-2cea6ce4f145.png)

**Comment by lantw44** [comment]
這裡的 result 是從 CEIBA API 來的，網頁上是不是用 iframe 應該不太重要。我猜把 `contents` 和 `content_files` 從 `result_keys` 移進 `optional_keys`，然後去下面 `# contents + content_files` 那邊加個 if 判斷，可能可以解決問題。

**Comment by lantw44** [comment]
Does this patch work for you?
```diff
diff --git a/ceiba_dl/vfs.py b/ceiba_dl/vfs.py
index fa95929..907d3c7 100644
--- a/ceiba_dl/vfs.py
+++ b/ceiba_dl/vfs.py
@@ -887,9 +887,10 @@ class CourseDirectory(Directory):
              'course_sn': self._sn,
              'class_no': self._class_no})
         result_keys = [
-            'lang', 'course_info', 'teacher_info', 'contents', 'content_files']
+            'lang', 'course_info', 'teacher_info']
         optional_keys = [
-            'bulletin', 'board', 'course_grade', 'homeworks']
+            'bulletin', 'contents', 'content_files', 'board',
+            'course_grade', 'homeworks']
         assert set(result.keys()) - set(optional_keys) == set(result_keys)
 
         # lang
@@ -933,8 +934,10 @@ class CourseDirectory(Directory):
                 self.vfs, self, self._sn, result['bulletin']))
 
         # contents + content_files
-        self.add(s['dir_course_contents'], CourseContentsDirectory(
-            self.vfs, self, self._sn, result['contents'], result['content_files']))
+        if 'contents' in result and 'content_files' in result:
+            self.add(s['dir_course_contents'],
+                CourseContentsDirectory(self.vfs, self, self._sn,
+                    result['contents'], result['content_files']))
 
         # board
         if 'board' in result:
```

**Comment by wheatdog** [comment]
Yes, it works flawlessly. Thank for your kindly support!
