### ISSUE TITLE
AssertionError in vfs.py line 2104

### ISSUE THREAD

**Issue by wheatdog** [lantw44/ceiba-dl#8]
I think we can just comment this assertion.

```
Traceback (most recent call last):                                                                                                                            
  File "/usr/bin/ceiba-dl", line 243, in <module>                                                                                                             
    exit(0 if args.func(args, config) else 1)                           
  File "/usr/bin/ceiba-dl", line 141, in run_get                             
    end_download_callback=end_callback)                                                                                                                       
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 388, in run                                                                              
    download_progress_callback, end_download_callback)                                                                                                        
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file                                                                    
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 214, in download_file
    node = self.vfs.open(path)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 2104, in fetch
    (grade['notes'], grade_row_notes)
AssertionError: ('第二週起，13:00至13:10有隨堂測驗，考試範圍為前一週的上課內容，題目通常會是比較經典的題目。\r\n(學生可以在「課程內容」下載練習題及參考答案，該
習題不需繳交。)\r\n得分較低的兩次不採計。\r\n評分標準大致分為四個層級：\r\n&#9312;學習態度\r\n&#9313;想法\r\n&#9314;觀念\r\n&#9315;計算與圖文表達', '第二週起，
13:00至13:10有隨堂測驗，考試範圍為前一週的上課內容，題目通常會是比較經典的題目。\r\n(學生可以在「課程內容」下載練習題及參考答案，該習題不需繳交。)\r\n得分較低
的兩次不採計。\r\n評分標準大致分為四個層級：\r\n①學習態度\r\n②想法\r\n③觀念\r\n④計算與圖文表達')
```

**Comment by lantw44** [comment]
> I think we can just comment this assertion.

No, the assertion here is intended to catch difference between CEIBA API and CEIBA web page. Ideally CEIBA API should be more correct since CEIBA web page is vulnerable to XSS attack. However, the undocumented API sometimes provides worse, or even wrong, data. In this case, the version extracted from the web page is better and the version returned by API should be fixed instead.

I just made a patch for the problem you mentioned above:
```diff
diff --git a/ceiba_dl/vfs.py b/ceiba_dl/vfs.py
index fa95929..5fcb66d 100644
--- a/ceiba_dl/vfs.py
+++ b/ceiba_dl/vfs.py
@@ -2099,6 +2103,7 @@ class CourseGradesDirectory(Directory):
                 # 已知 grade_isranking 的值很可能不正確，因此這裡直接忽略
                 # assert grade['grade_isranking'] == grade_row_grade_isranking
 
+                grade['notes'] = html.unescape(grade['notes'])
                 assert grade['notes'] == grade_row_notes, \
                     (grade['notes'], grade_row_notes)
 
```

**Comment by wheatdog** [comment]
Thanks for your detail explanation!
