### ISSUE TITLE
AssertionError in vfs.py line 1597

### ISSUE THREAD

**Issue by wheatdog** [lantw44/ceiba-dl#9]
I think is fine to comment this line, or add more logic in line 1594.

```
Traceback (most recent call last):
  File "/usr/bin/ceiba-dl", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "/usr/bin/ceiba-dl", line 141, in run_get
    end_download_callback=end_callback)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 388, in run
    download_progress_callback, end_download_callback)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 232, in download_file
    if not self.download_file(child_path, retry, dcb, ecb):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.7/site-packages/ceiba_dl/__init__.py", line 214, in download_file
    node = self.vfs.open(path)
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 40, in open
    work.fetch()
  File "/usr/lib/python3.7/site-packages/ceiba_dl/vfs.py", line 1597, in fetch
    assert self._hw['description'] == hw_show_description
AssertionError
```

self._hw['description']:
```
請將作業放進"(學號)_hw2"資料夾，再打包成zip檔上傳<BR>
ex. B03902001_hw2.zip解壓縮後應該要有B03902001_hw2的資料夾存在，裡面只放.hdl檔謝謝
```
hw_show_description:
```
請將作業放進"(學號)_hw2"資料夾，再打包成zip檔上傳
ex. B03902001_hw2.zip解壓縮後應該要有B03902001_hw2的資料夾存在，裡面只放.hdl檔謝謝
```

**Comment by lantw44** [comment]
> I think is fine to comment this line, or add more logic in line 1594.

It should be easy to fix:
```diff
diff --git a/ceiba_dl/vfs.py b/ceiba_dl/vfs.py
index fa95929..5fcb66d 100644
--- a/ceiba_dl/vfs.py
+++ b/ceiba_dl/vfs.py
@@ -1589,6 +1592,7 @@ class CourseHomeworksHomeworkDirectory(Directory):
 
             self._hw['description'] = html.unescape(self._hw['description']) \
                 .replace('<br>', '').replace('</br>', '') \
+                .replace('<BR>', '').replace('</BR>', '') \
                 .replace('∼', '～').replace('•', '‧')
             hw_show_description = hw_show_description.replace('∼', '～')
             assert self._hw['description'] == hw_show_description
```

**Comment by wheatdog** [comment]
You are right. It did fix the problem. Thanks again for your kindly support!
